### ISSUE TITLE
Task 1 Milestone 1 v0.5

### ISSUE THREAD

**Issue by dbc2201** [daminisingh97/E-Cops#1]
Task 1 is to create mockups for your application.
[Here's](https://www.uxpin.com/studio/blog/what-is-a-mockup-the-final-layer-of-ui-design/) a guide to mockups.
You may use either of the following software
1. JustInMind - https://www.justinmind.com/
2. Balsamiq Mockups Pro - https://balsamiq.com/wireframes/desktop/ Balsamiq is a paid software and would require a license, write an email to me for the license info.

**Comment by dbc2201** [comment]
Mock-ups not published yet.

**Comment by basilbaig** [comment]
[newecops.pdf.pdf](https://github.com/daminisingh97/E-Cops/files/2953360/newecops.pdf.pdf)
