### ISSUE TITLE
Task 10 - Complete the SRS document.

### ISSUE THREAD

**Issue by dbc2201** [daminisingh97/E-Cops#10]
- [ ] Find the format for the SRS doc in your email.

- [ ] Complete the doc for submission before 14th March.

**Comment by kashish459** [comment]
[ecopssrs.pdf](https://github.com/daminisingh97/E-Cops/files/2973425/ecopssrs.pdf)

**Comment by kashish459** [comment]
[ecopssrs.pdf](https://github.com/daminisingh97/E-Cops/files/3031927/ecopssrs.pdf)
