### ISSUE TITLE
Task 12 - Shift documentation to the wiki pages

### ISSUE THREAD

**Issue by dbc2201** [daminisingh97/E-Cops#12]
- [ ] Create wiki pages for your repository.

### Extra 
[GitHub Wiki Pages Guide ](https://help.github.com/en/articles/adding-or-editing-wiki-pages)

**Comment by arbaz987** [comment]
[srs.pdf](https://github.com/daminisingh97/E-Cops/files/3056834/srs.pdf)
[synopsis.pdf](https://github.com/daminisingh97/E-Cops/files/3056836/synopsis.pdf)
Wiki pages have been created.
