### ISSUE TITLE
Task 4 - Publish the mock-ups to the project repo.

### ISSUE THREAD

**Issue by dbc2201** [daminisingh97/E-Cops#4]
- [ ] Export individual mock-up screens into separate PNG image files.
- [ ] Place the images in a separate location in your repository, preferably "./images/mockups/".
- [ ] Update your readme.md file, add a new heading (L3/L4) named "mock-up screens" and add the image files there, neatly labelled.

**Comment by basilbaig** [comment]
Task4 done sir
