### ISSUE TITLE
Task 5 - Create wireframes for your project.

### ISSUE THREAD

**Issue by dbc2201** [daminisingh97/E-Cops#5]
- [x] Integrate your mock-ups to create a wireframe.
This wireframe will be the single source of information of all the interaction among different screens in your software
### Extra
[Intro to Wireframing, by the nice people at Balsamiq](https://balsamiq.com/learn/courses/wireframing/)

**Comment by basilbaig** [comment]
[wireframe.pdf](https://github.com/daminisingh97/E-Cops/files/2958142/wireframe.pdf)

**Comment by basilbaig** [comment]
wireframe done sir
